version: '3.9'

services:
  php:
    restart: always
    container_name: app-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    working_dir: /var/www/html
    expose:
      - ${PHP_INTERNAL_PORT:-9000}
    volumes:
      - ./:/var/www/html
    networks:
      default:
        ipv4_address: 172.20.0.10

  web:
      restart: always
      container_name: app-nginx
      build:
        context: ./docker/nginx
        dockerfile: Dockerfile
      volumes:
        - ./:/var/www/html
      ports:
        - "80:80"
      networks:
        default:
          ipv4_address: 172.20.0.20

  mysql:
    restart: always
    container_name: app-mysql
    command: --default-authentication-plugin=mysql_native_password
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-learn}
      MYSQL_USER: ${MYSQL_USER:-learn}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-123456}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
    ports:
      - "3310:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      default:
        ipv4_address: 172.20.0.35

networks:
  default:
    driver: bridge
    name: default_network
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  myapp:
    driver: local
